<a href="https://colab.research.google.com/github/walaa-coder1/Task-iti/blob/main/Python_Numpy_Exercises_with_hints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python NumPy Exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` and print the numpy version and the configuration (★☆☆)

`Hint: import … as` and `np.__version__, np.show_config)`

In [9]:
import numpy as np
print(np.__version__)
np.show_config()

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.11.8/lib/python3.11/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

#### 2. Convert a list of numeric value into a one-dimensional NumPy array (★☆☆)
`💡 hint: numpy.array`

In [10]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)
print(arr)



[1 2 3 4 5]


#### 3. Create a null vector of size 9 (★☆☆)
`💡 hint: np.zeros`

In [11]:
z = np.zeros(9)
print(z)



[0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)
`💡 hint: size, itemsize`

In [13]:
z = np.zeros((4, 4))
print(z.size * z.itemsize, "bytes")





128 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
`💡hint: np.info`

In [14]:
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 12 but the sixth value which is 1 (★☆☆)
`💡hint: array[12]`

In [15]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 20 to 59 (★☆☆)
`💡hint: arange`

In [16]:
z = np.arange(10, 50)
print(z)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)
`💡hint: array[::-1]`

In [17]:
z = np.arange(10)
print(z[::-1])


[9 8 7 6 5 4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 12 to 20 (★☆☆)
`💡hint: reshape`

In [18]:
z = np.arange(9).reshape(3, 3)
print(z)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [3,7,0,0,9,0] (★☆☆)
`💡hint: np.nonzero`

In [19]:
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)


(array([0, 1, 4]),)


#### 11. Create a 4x4 identity matrix (★☆☆)
`💡hint: np.eye`

In [20]:
z = np.eye(3)
print(z)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 2x2x2 array with random values (★☆☆)
`💡hint: np.random.random`

In [21]:
z = np.random.random((3, 3, 3))
print(z)


[[[0.07786555 0.20486349 0.02827907]
  [0.41015221 0.17156601 0.24656375]
  [0.39005219 0.65226227 0.05616991]]

 [[0.60625849 0.03999308 0.66769529]
  [0.44560126 0.99955172 0.15945177]
  [0.11642286 0.8143257  0.14625699]]

 [[0.87629446 0.2726281  0.71104802]
  [0.56387538 0.87386589 0.34618818]
  [0.25259609 0.21045781 0.43956241]]]


#### 13. Create a 9x9 array with random values and find the minimum and maximum values (★☆☆)
`💡hint: min, max`

In [22]:
z= np.random.random((10, 10))
print(z.min(), z.max())



0.015589850652984238 0.9949140398777276


#### 14. Create a random vector of size 20 and find the mean value (★☆☆)
`💡hint: mean`

In [23]:
z = np.random.random(30)
print(z.mean())


0.46222117601828955


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
`💡hint: array[1:-1, 1:-1]`

In [24]:
z= np.zeros((8, 8))
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)



[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
`💡hint: np.pad`

In [25]:
z = np.random.random((5, 5))
zmin, zmax = z.min(), z.max()
z = (z - zmin) / (zmax - zmin)
print(z)

[[0.33506315 0.22058346 0.74600198 0.60762906 0.12000969]
 [0.98037324 0.6098655  0.52422814 0.70214051 0.45325914]
 [0.33052384 0.4376606  0.03293876 1.         0.19891519]
 [0.45069085 0.84361153 0.         0.80846734 0.51802287]
 [0.77401315 0.40536284 0.01848795 0.19939841 0.70787219]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```
`💡hint: NaN = not a number, inf = infinity`

In [26]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.7 == 7 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 6x6 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`💡hint: np.diag`

In [27]:
z = np.diag(np.arange(1, 5), k=0)
print(z)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 6x6 matrix and fill it with a checkerboard pattern (★☆☆)
`💡hint: array[::2]`

In [28]:
z = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
`💡hint: np.unravel_index`

In [29]:
z=np.random.random((5, 5))
z = (z - np.min(z)) / (np.max(z) - np.min(z))
print(z)

[[0.47562367 0.60354153 0.01046669 0.94375072 0.50413279]
 [0.99728211 0.83782007 0.75707725 0.21084304 0.08684322]
 [0.33486574 0.05576353 1.         0.1511165  0.        ]
 [0.77307758 0.65458728 0.0371758  0.34915747 0.38317188]
 [0.96818143 0.21084465 0.55913746 0.73894065 0.19007448]]


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
`💡hint: np.tile`

In [30]:
a= np.array([1, 2, 3, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6])
print(np.intersect1d(a, b))


[3 4 5]


#### 22. Normalize a 6x6 random matrix (★☆☆)
`💡hint: (x -mean)/std`

In [31]:
today = np.datetime64('today', 'D')
print(today - np.timedelta64(1, 'D'))
print(today)
print(today + np.timedelta64(1, 'D'))



2025-08-15
2025-08-16
2025-08-17


#### 23. find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. (★☆☆)

In [32]:
z = np.arange('2025-08', '2025-09', dtype='datetime64[D]')
print(z)


['2025-08-01' '2025-08-02' '2025-08-03' '2025-08-04' '2025-08-05'
 '2025-08-06' '2025-08-07' '2025-08-08' '2025-08-09' '2025-08-10'
 '2025-08-11' '2025-08-12' '2025-08-13' '2025-08-14' '2025-08-15'
 '2025-08-16' '2025-08-17' '2025-08-18' '2025-08-19' '2025-08-20'
 '2025-08-21' '2025-08-22' '2025-08-23' '2025-08-24' '2025-08-25'
 '2025-08-26' '2025-08-27' '2025-08-28' '2025-08-29' '2025-08-30'
 '2025-08-31']


#### 24. Multiply a 6x3 matrix by a 3x4 matrix (real matrix product) (★☆☆)
`💡hint: np.dot` or `np.ones`

In [33]:
delta = np.datetime64('2025-08-13') - np.datetime64('2025-07-01')
print(delta)


43 days


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
`💡hint: >, <`

In [34]:
z = np.diag(1 + np.arange(4), k=-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 26. What is the output of the following script? (★☆☆)
```python

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [35]:
z= np.random.random((10, 10))
z.sort(axis=1)
print(z)


[[1.11767281e-01 1.68171368e-01 2.86681787e-01 2.98339577e-01
  3.98814226e-01 4.08131302e-01 4.80272987e-01 6.52777531e-01
  6.83212654e-01 7.83420370e-01]
 [1.76092604e-01 1.91178677e-01 1.95087234e-01 2.66238315e-01
  4.19239297e-01 5.13568404e-01 5.15440524e-01 6.79383852e-01
  8.05506326e-01 8.07363911e-01]
 [2.89894500e-02 2.31759396e-01 2.59608675e-01 3.67423788e-01
  7.33778266e-01 7.44260518e-01 7.48079788e-01 8.61781734e-01
  8.92484915e-01 9.86538749e-01]
 [1.94800932e-02 3.72166430e-02 5.50004683e-01 7.32766042e-01
  7.68331932e-01 7.71125283e-01 7.91380356e-01 8.99633799e-01
  9.30048868e-01 9.32627649e-01]
 [5.03151838e-03 4.00178166e-01 5.17879457e-01 5.29150176e-01
  6.35265679e-01 6.80659149e-01 7.25448156e-01 7.86537089e-01
  8.34607679e-01 9.31046771e-01]
 [1.33618454e-01 1.75735452e-01 2.50308203e-01 3.00150429e-01
  4.21608372e-01 5.14822241e-01 5.35037033e-01 6.24178294e-01
  6.75712503e-01 9.97529833e-01]
 [2.44672875e-02 1.34304409e-01 2.24471153e-01 2.28021517e

#### 27. Write a Python program compare two arrays using numpy (★☆☆)
```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [36]:
a = np.random.randint(0, 2, 5)
b = np.random.randint(0, 2, 5)
equal = np.allclose(a, b)
print(equal)


False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```
Consider an integer vector a
```python
a**a
a << a >> 2
a <- a
1j*a
a/1/1
a<a>a
```

In [37]:
np.seterr(all='ignore')
np.seterr(over='raise')



{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 29. How to round away from zero a float array ? (★☆☆)
`💡hint: np.uniform, np.copysign, np.ceil, np.abs, np.where`

In [38]:
z = np.random.random((10, 2))
length = np.sqrt(z**2).sum(axis=1)
print(length)


[1.03246522 0.54727395 0.95360496 1.00345981 1.32957852 1.02894014
 0.73509658 1.64476882 0.47822106 0.81656602]


#### 30. How to find common values between two arrays? (★☆☆)
`💡hint: np.intersect1d`

In [39]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)



[[-0.22573199  0.27715007  0.31603707 -0.14931849  0.33368155 -0.30831069
   0.18221305  0.3548748  -0.28013386 -0.50046151]
 [-0.39792853 -0.27322735 -0.16284312 -0.23093214  0.25458843  0.08065369
   0.20470963  0.31825422 -0.05255386  0.25927902]
 [ 0.20249112  0.31816379 -0.3703528  -0.26302328  0.18377961 -0.01429426
  -0.01692169 -0.28245354  0.22899443  0.01361662]
 [-0.13564759 -0.35114999  0.34443428  0.01712037  0.1100938  -0.21469596
   0.17340775  0.33016121 -0.2966111   0.02288722]
 [-0.15691604 -0.42464589  0.06070048  0.04844962  0.27073464  0.1734916
   0.09863181  0.42560118 -0.36583323 -0.13021417]]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
`💡hint: np.seterr, np.errstate`

In [40]:
Z = np.random.randint(0, 10, (3, 3))
print(Z[Z[:, 1].argsort()])



[[8 3 9]
 [1 3 1]
 [9 5 9]]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```
`💡hint: imaginary number`

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
`💡hint: np.datetime64, np.timedelta64`

#### 34. How to get all the dates corresponding to the month of January 2016? (★★☆)
`💡hint: np.arange(dtype=datetime64['D'])`

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
`💡hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=)`

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
`💡hint: %, np.floor, astype, np.trunc`

#### 37. Create a 3x3 matrix with row values ranging from 0 to 2 (★★☆)
`💡hint: np.arange`

#### 38. Consider a generator function that generates 9 integers and use it to build an array (★☆☆)
`💡hint: np.fromiter`

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
`💡hint: np.linspace`

#### 40. Create a random vector of size 10 and sort it (★★☆)
`💡hint: sort`

#### 41. How to sum a small array faster than np.sum? (★★☆)
`💡hint: np.add.reduce`

#### 42. Consider two random array A and B, check if they are equal (★★☆)
`💡hint: np.allclose, np.array_equal`

#### 43. Make an array immutable (read-only) (★★☆)
`💡hint: flags.writeable`

#### 44. Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
`💡hint: np.sqrt, np.arctan2`

#### 45. Create random vector of size 5 and replace the maximum value by 0 (★★☆)
`💡hint: argmax`

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
`💡hint: np.meshgrid`

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)
`💡hint: np.subtract.outer`

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
`💡hint: np.iinfo, np.finfo, eps`

#### 49. How to print all the values of an array? (★★☆)
`💡hint: np.set_printoptions`

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
`💡hint: argmin`

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
`💡hint: dtype`

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
`💡hint: np.atleast_2d, T, np.sqrt`

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
`💡hint: view and [:] =`

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```
`💡hint: np.genfromtxt`

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
`💡hint: np.ndenumerate, np.ndindex`

#### 56. Generate a generic 2D Gaussian-like array (★★☆)
`💡hint: np.meshgrid, np.exp`

#### 57. How to randomly place e elements in a 2D array? (★★☆)
`💡hint: np.put, np.random.choice`

#### 58. Subtract the mean of each row of a matrix (★★☆)
`💡hint: mean(axis=,keepdims=)`

#### 59. How to sort an array by the nth column? (★★☆)
`💡hint: argsort`

#### 60. How to tell if a given 2D array has null columns? (★★☆)
`💡hint: any, ~`

#### 61. Find the nearest value from a given value in an array (★★☆)
`💡hint: np.abs, argmin, flat`

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
`💡

#### 63. Create an array class that has a name attribute (★★☆)
`💡hint: class method`

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
`💡hint: np.bincount | np.add.at`

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
`💡hint: np.bincount`

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)
`💡hint: np.unique`

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
`💡hint: sum(axis=(-2,-1))`

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)
`💡hint: np.bincount`

#### 69. How to get the diagonal of a dot product? (★★★)
`💡hint: np.diag`

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
`💡hint: array[::4]`

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
`💡hint: array[:, :, None]`

#### 72. How to swap two rows of an array? (★★★)
`💡hint: array[[]] = array[[]]`

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
`💡hint: repeat, np.roll, np.sort, view, np.unique`

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
`💡hint: np.repeat`

#### 75. How to compute averages using a sliding window over an array? (★★★)
`💡hint: np.cumsum`

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
`💡hint: from numpy.lib import stride_tricks`

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
`💡hint: np.logical_not, np.negative`

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
`💡hint: minimum maximum`

#### 81. Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
`💡hint: stride_tricks.as_strided`

#### 82. Compute a matrix rank (★★★)
`💡hint: np.linalg.svd`

#### 83. How to find the most frequent value in an array?
`💡hint: np.bincount, argmax`

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
`💡hint: stride_tricks.as_strided`

#### 85. Create a 2D array subclass such that a[i,j] == a[j,i] (★★★)
`💡hint: class method`

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
`💡hint: np.tensordot`

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
`💡hint: np.add.reduceat`

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)
`💡hint: np.argsort | np.argpartition`

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
`💡hint: np.indices`

#### 91. How to create a record array from a regular array? (★★★)
`💡hint: np.core.records.fromarrays`

#### 92. Consider a large vector A, compute A to the power of 3 using 3 different methods (★★★)
`💡hint: np.power, *, np.einsum`

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
`💡hint: np.where`

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
`💡hint: np.unpackbits`

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
`💡hint: np.ascontiguousarray | np.unique`

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
`💡hint: np.einsum`

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
`💡hint: np.cumsum, np.interp`

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
`💡hint: np.logical_and.reduce, np.mod`

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
`💡hint: np.percentile`